export default
{
    "American": "US",
    "USA": "US",
    "Austrian": "AT",
    "Australian": "AU",
    "Bahrain": 'BH',
    "British": "GB",
    "Canadian": "CA",
    "Danish": "DK",
    "Dutch": "NL",
    "Finnish": "FI",
    "French": "FR",
    "German": "DE",
    "Italian": "IT",
    "Japanese": "JP",
    "Monegasque": "MC",
    "Mexican": "MX",
    "Russian": "RU",
    "Spanish": "ES",
    "Thai": "TH",
    "Turkey": 'TR',
    "UAE": 'AE',
    "Brazilian": 'BR',
    "Portugal": 'PT',
    "Chinese": "CN",
    "Argentinian": "AR"
}